/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_heart_rate_0                   19
#define gattdb_heart_rate_measurement         21
#define gattdb_pulse_oximeter_0               23
#define gattdb_plx_spot_check_measurement     25
#define gattdb_plx_continuous_measurement     28
#define gattdb_StepCounter                    30
#define gattdb_Steps                          32


#endif // __GATT_DB_H
